[package]
name = "dynamixel-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.10"
spin = "0.9.3"

[features]
default = ["xc330"]
xc330 = []